#oltp_only ou htap
run.mode=htap

#Threads OLTP
oltp.threads=7
oltp.txPerThread=5000
oltp.batchSize=800

#Threads OLAP
olap.threads=3

#fichiers sql workloads
workload.oltp=workload/oltp.sql
workload.olap=workload/olap.sql

#fichier de métriques
metrics.file=/data/metrics/htap_metrics.csv

run.durationSeconds=60

