#oltp_only | htap | oltp
run.mode=htap

#jdbc | api
client.mode=jdbc

#Threads OLTP
oltp.threads=8
oltp.txPerThread=100000
oltp.batchSize=1000

#Threads OLAP
olap.threads=3

#fichiers sql workloads
workload.oltp=workload/oltp.sql
workload.olap=workload/olap.sql
populate.oltp =workload/populate.sql
workload.olap_only =workload/olap_only.sql

#fichier de métriques
metrics.file=/data/metrics/htap_metrics.csv

run.durationSeconds=70

