# proxy.properties
postgres.url=jdbc:postgresql://postgres:5432/htapdb?user=htap&password=htap
clickhouse.url=jdbc:clickhouse://clickhouse:8123/default?user=default&password=clickhouse&use_http_transport=true
