version: '3.8'

services:

  postgres:
    image: debezium/postgres:15
    container_name: htap-postgres
    environment:
      POSTGRES_USER: htap
      POSTGRES_PASSWORD: htap
      POSTGRES_DB: htapdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - htap-net

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: htap-clickhouse
    ports:
      - "8123:8123"    # HTTP
      - "9000:9000"    # Native
    depends_on:
      - kafka
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/kafka.xml
    networks:
      - htap-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: htap-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - htap-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: htap-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - htap-net

  connect:
    image: debezium/connect:2.6
    container_name: htap-connect
    depends_on:
      - kafka
      - postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium-config
      OFFSET_STORAGE_TOPIC: debezium-offsets
      STATUS_STORAGE_TOPIC: debezium-status
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    volumes:
      - ./connectors:/kafka/connectors
    networks:
      - htap-net

  init-connect:
    image: curlimages/curl:8.2.1
    depends_on:
      - connect
    volumes:
      - ./connectors:/kafka/connectors
      - ./init-connect.sh:/init-connect.sh
    entrypoint: [ "/bin/sh", "/init-connect.sh" ]
    networks:
      - htap-net

#  proxy:
#    build:
#      context: ../proxy
#    container_name: htap-proxy
#    stdin_open: true
#    tty: true
#    depends_on:
#      - postgres
#      - clickhouse
#    environment:
#      POSTGRES_URL: jdbc:postgresql://postgres:5432/htapdb?user=htap&password=htap
#      CLICKHOUSE_URL: jdbc:clickhouse://clickhouse:8123/default?user=default&password=clickhouse&use_http_transport=true
#    networks:
#      - htap-net

  proxy:
    build:
      context: ../proxy
    container_name: htap-proxy
    depends_on:
      - postgres
      - clickhouse
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/htapdb?user=htap&password=htap
      CLICKHOUSE_URL: jdbc:clickhouse://clickhouse:8123/default?user=default&password=clickhouse&use_http_transport=true
    ports:
      - "8080:8080"
    networks:
      - htap-net

  benchmark:
    build:
      context: ../benchmark
    container_name: htap-benchmark
    depends_on:
      - proxy
    environment:
      # Si besoin de paramètres (nb de threads, durée, etc.)
      PROXY_URL: http://htap-proxy:8080/proxy/query
    networks:
      - htap-net


  sink:
    build:
      context: ../sink
    container_name: htap-sink
    depends_on:
      - kafka
      - clickhouse
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      CLICKHOUSE_URL: jdbc:clickhouse://clickhouse:8123/default?user=default&password=clickhouse&use_http_transport=true
      POSTGRES_URL: jdbc:postgresql://postgres:5432/htapdb?user=htap&password=htap
    restart: always
    networks:
      - htap-net

volumes:
  postgres_data:
  clickhouse_data:

networks:
  htap-net:
    driver: bridge
