package com.htap.meta;

import java.sql.*;
import java.util.*;

public class HTAPStatement implements Statement {

    protected final HTAPConnection conn;
    protected final List<String> batch = new ArrayList<>();
    protected HTAPResultSet resultSet;
    protected int updateCount = 0;
    private boolean closed = false;


    HTAPStatement(HTAPConnection conn) {
        this.conn = conn;
    }

    // Dans HTAPStatement.java (hérité par Prepared)
    public static List<Map<String,Object>> adaptResult(Object res) throws SQLException {
        if (res instanceof List) return (List<Map<String,Object>>) res;
        if (res instanceof Number) {
            List<Map<String,Object>> rows = new ArrayList<>();
            Map<String,Object> row = new HashMap<>();
            row.put("result", res);
            rows.add(row);
            return rows;
        }
        if (res == null) return new ArrayList<>();
        throw new SQLException("Unexpected: " + res.getClass());
    }


    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        Object res = HttpClient.post(conn.endpoint, "/proxy/query", sql);
        List<Map<String,Object>> rows = adaptResult(res);
        this.resultSet = new HTAPResultSet(rows, this);
        return this.resultSet;
    }

    @Override
    public int executeUpdate(String sql) {
        Object res = HttpClient.post(conn.endpoint, "/proxy/query", sql);
        updateCount = (res instanceof Number) ? ((Number) res).intValue() : 0;
        return updateCount;
    }

    @Override
    public void close() {
        closed = true;
        resultSet = null;
        batch.clear();
    }


    @Override
    public int getMaxFieldSize() throws SQLException {
        return 0;
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {

    }

    @Override
    public int getMaxRows() throws SQLException {
        return 0;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {

    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {

    }

    @Override
    public int getQueryTimeout() throws SQLException {
        return 0;
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {

    }

    @Override
    public void cancel() throws SQLException {

    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return null;
    }

    @Override
    public void clearWarnings() throws SQLException {

    }

    @Override
    public void setCursorName(String name) throws SQLException {

    }

    @Override
    public boolean execute(String sql) throws SQLException {
        Object res = HttpClient.post(conn.endpoint, "/proxy/query", sql);
        List<Map<String,Object>> rows = adaptResult(res);
        if (rows != null) {
            resultSet = new HTAPResultSet(rows, this);
            updateCount = -1;
            return true;
        }
        this.updateCount = (res instanceof Number) ? ((Number)res).intValue() : 0;
        return false;  // update count
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return resultSet;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return updateCount;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return false;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {

    }

    @Override
    public int getFetchDirection() throws SQLException {
        return 0;
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {

    }

    @Override
    public int getFetchSize() throws SQLException {
        return 0;
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return ResultSet.CONCUR_READ_ONLY;
    }

    @Override
    public int getResultSetType() throws SQLException {
        return ResultSet.TYPE_FORWARD_ONLY;
    }

    @Override
    public void addBatch(String sql) {
        batch.add(sql);
    }

    @Override
    public void clearBatch() {
        batch.clear();
    }

    @Override
    public int[] executeBatch() {
        HttpClient.postBatch(conn.endpoint, batch);
        int[] res = new int[batch.size()];
        Arrays.fill(res, 1);
        batch.clear();
        return res;
    }

    @Override
    public Connection getConnection() throws SQLException {
        return conn;
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return false;
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return null;
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return 0;
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return 0;
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return 0;
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return false;
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return false;
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return false;
    }

    @Override
    public int getResultSetHoldability() {
        return ResultSet.CLOSE_CURSORS_AT_COMMIT;
    }


    @Override
    public boolean isClosed() throws SQLException {
        return closed;
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {

    }

    @Override
    public boolean isPoolable() throws SQLException {
        return false;
    }

    @Override
    public void closeOnCompletion() throws SQLException {

    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return false;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("Not a wrapper");
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) {
        return iface.isInstance(this);
    }

    /* addBatch / executeBatch → important pour perf */
}
