package com.htap.meta.jdbc;

import com.htap.meta.ExecutorFactory;
import com.htap.meta.analyze.QueryAnalyzer;
import com.htap.meta.routing.QueryRouter;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * Connection JDBC proxy pour HTAP.
 * Toutes les requêtes passent par QueryRouter.
 */
public class Connection implements Connection {

    private final QueryRouter router;

    public Connection(Properties info) throws SQLException {
        ExecutorFactory factory = new ExecutorFactory(); // lit les URLs depuis les variables d'env
        QueryAnalyzer analyzer = new QueryAnalyzer();
        this.router = new QueryRouter(analyzer, factory);
    }

    @Override
    public Statement createStatement() throws SQLException {
        return new Statement(router);
    }

    @Override
    public void close() throws SQLException {}

    @Override
    public boolean isClosed() { return false; }

    @Override
    public void commit() throws SQLException {}
    @Override
    public void rollback() throws SQLException {}
    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {}
    @Override
    public boolean getAutoCommit() throws SQLException { return true; }

    // --- Stubs pour toutes les autres méthodes non utilisées
    @Override public PreparedStatement prepareStatement(String sql) { throw new UnsupportedOperationException(); }
    @Override public CallableStatement prepareCall(String sql) { throw new UnsupportedOperationException(); }
    @Override public String nativeSQL(String sql) { throw new UnsupportedOperationException(); }
    @Override public DatabaseMetaData getMetaData() { throw new UnsupportedOperationException(); }
    @Override public void setReadOnly(boolean readOnly) { }
    @Override public boolean isReadOnly() { return false; }
    @Override public void setCatalog(String catalog) { }
    @Override public String getCatalog() { return null; }
    @Override public void setTransactionIsolation(int level) { }
    @Override public int getTransactionIsolation() { return Connection.TRANSACTION_NONE; }
    @Override public SQLWarning getWarnings() { return null; }
    @Override public void clearWarnings() {}
    @Override public void setHoldability(int holdability) {}
    @Override public int getHoldability() { return ResultSet.CLOSE_CURSORS_AT_COMMIT; }
    @Override public Savepoint setSavepoint() { throw new UnsupportedOperationException(); }
    @Override public Savepoint setSavepoint(String name) { throw new UnsupportedOperationException(); }
    @Override public void rollback(Savepoint savepoint) { }
    @Override public void releaseSavepoint(Savepoint savepoint) { }
    @Override public Statement createStatement(int resultSetType, int resultSetConcurrency) { throw new UnsupportedOperationException(); }
    @Override public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) { throw new UnsupportedOperationException(); }
    @Override public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) { throw new UnsupportedOperationException(); }
    @Override public PreparedStatement prepareStatement(String sql, int[] columnIndexes) { throw new UnsupportedOperationException(); }
    @Override public PreparedStatement prepareStatement(String sql, String[] columnNames) { throw new UnsupportedOperationException(); }
    @Override public Clob createClob() { throw new UnsupportedOperationException(); }
    @Override public Blob createBlob() { throw new UnsupportedOperationException(); }
    @Override public NClob createNClob() { throw new UnsupportedOperationException(); }
    @Override public SQLXML createSQLXML() { throw new UnsupportedOperationException(); }
    @Override public boolean isValid(int timeout) { return true; }
    @Override public void setClientInfo(String name, String value) {}
    @Override public void setClientInfo(Properties properties) {}
    @Override public String getClientInfo(String name) { return null; }
    @Override public Properties getClientInfo() { return new Properties(); }
    @Override public Array createArrayOf(String typeName, Object[] elements) { throw new UnsupportedOperationException(); }
    @Override public Struct createStruct(String typeName, Object[] attributes) { throw new UnsupportedOperationException(); }
    @Override public void setSchema(String schema) { }
    @Override public String getSchema() { return null; }
    @Override public void abort(Executor executor) {}
    @Override public void setNetworkTimeout(Executor executor, int milliseconds) {}
    @Override public int getNetworkTimeout() { return 0; }
    @Override public <T> T unwrap(Class<T> iface) { throw new UnsupportedOperationException(); }
    @Override public boolean isWrapperFor(Class<?> iface) { return false; }
}
